package com.maksudsharif.migration.model;

public final class HeaderConstants
{
    public static final String INDEX = "Index";
    public static final String CREATED_DATE = "Created Date";
    public static final String FACILITY_NAME = "Facility Name";
    public static final String DUNS_NUM = "DUNS#";
    public static final String INITIAL_AUDIT_START_DATE = "Initial Audit Start Date";
    public static final String INITIAL_AUDIT_END_DATE = "Initial Audit End Date";
    public static final String RESPONSIBLE_AOID = "Responsible AO (4-character AOID)";
    public static final String JURISDICTION = "Jurisdiction (1 or more)";
    public static final String OTHER_TRADE_NAMES = "Name";
    public static final String CAMPUS = "Campus (Yes/No)";
    public static final String AO_CLIENT_REFERENCE_NUM = "AO Client Reference #";
    public static final String PRIMARY_CAMPUS = "Primary Campus";
    public static final String CAMPUS_BUILDING_NAME = "Campus Building Name";
    public static final String ADDRESSES = "Addresses";
    public static final String ADDRESS_1 = "Address 1";
    public static final String COUNTRY = "Country";
    public static final String ADDRESS_2 = "Address 2";
    public static final String CITY = "City";
    public static final String STATE_PROVINCE = "State/Province";
    public static final String ZIP_POSTAL_CODE = "ZIP/Postal Code";
    public static final String TGA_LOCATION_ID = "TGA Location ID";
    public static final String MHLW_PMDA_REGISTRATION_NUM = "MHLW/PMDA Registration #";
    public static final String FDA_REGISTRATION_NUM = "FDA - Registration #";
    public static final String FDA_FEI = "FDA - FEI";
    public static final String FDA_DISTRICT = "FDA - District";
    public static final String BRAZILIAN_GMP_REQUEST_NUM = "Brazilian GMP Request #";
    public static final String ANVISA_NUM = "ANVISA #";
    public static final String FACILITY_ACTIVITIES = "Facility Activities";
    public static final String CERTIFICATE_HOLDER = "Certificate Holder (Yes/No)";
    public static final String TGA_CLIENT_ID = "TGA - Client ID";
    public static final String HC_COMPANY_ID = "HC - Company ID";
    public static final String SCOPE_OF_MDSAP_CERTIFICATION = "Scope of MDSAP Certification";
    public static final String RELATED_CERTIFICATE_HOLDER_FIRM_NAME = "Related Certificate Holder Firm Name";
    public static final String PHONE_NUMBER = "Phone Number";
    public static final String PHONE_TYPE = "Phone Type";
    public static final String FAX = "Fax";
    public static final String FAX_TYPE = "Fax Type";
    public static final String EMAIL = "eMail";
    public static final String EMAIL_TYPE = "eMail Type";
    public static final String URL = "URL";
    public static final String URL_TYPE = "URL Type";
    public static final String ADDITIONAL_INFORMATION = "Additional Information";
    public static final String LAST_NAME = "Last Name";
    public static final String FIRST_NAME = "First Name";
    public static final String CONTACT_PERSON_PHONE_NUMBER = "Contact Person Phone Number";
    public static final String CONTACT_PERSON_EMAIL = "Contact Person eMail";
    public static final String TITLE = "Title";
    public static final String CONTACT_PERSON_PRIMARY_YES_NO = "Primary Yes/No";
    public static final String CONTACT_PERSONS = "Contact Persons";
    public static final String CERTIFICATE_HOLDERS = "Certificate Holders";
}
